version: "3.7"
services:
    db:
        image: mysql:latest
        restart: always
        container_name: mysql_racedb_app
        command: --default-authentication-plugin=mysql_native_password
        env_file: ./dbconfig.env
        networks:
            racedb:
                aliases:
                    - database
        hostname: mysql_racedb_app
        volumes:
            - mysql-data:/var/lib/mysql
            - mysql-run:/var/run/mysqld
                
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        restart: always
        container_name: phpmyadmin_racedb_app
        env_file: ./dbconfig.env
        environment:
            - PMA_HOST=db
        ports:
            - "8080:80"
            - "8443:443"
        hostname: phpmyadmin_app
        networks:
            racedb:
                aliases:
                    - phpmyadmin
        depends_on:
            - db
        volumes:
            - mysql-data:/var/lib/mysql
            - mysql-run:/var/run/mysqld

    racedb:
        image: mbuckaway/racedb-mysql:beta
        restart: always
        container_name: racedb_app
        ports:
            - "80:80"
        env_file:
            - ./racedb.env
        environment:
            - sqlite3_database_fname:/racedb-data/RaceDB.sqlite3
            - PYTHONPATH:/RaceDB
            - RACEDBLOGFILE:/racedb-data/RaceDB-log.txt
        hostname: racedb_app
        networks:
            racedb:
                aliases:
                    - racedb
        depends_on:
            - db
        volumes:
            - racedb-data:/racedb-data
            # These two are only used during development
            - ./docker-entrypoint-init.d:/docker-entrypoint-init.d
            - ./RaceDB:/RaceDB

volumes:
    mysql-data:
    mysql-run:
    racedb-data:

networks:
    racedb:

